### ISSUE TITLE
Dynamic cell backgrounds

### ISSUE THREAD

**Issue by picotrain1** [newky2k/dscomponents#1]
Hi,

Great component!

As it exists, is it possible to dynamically change the CellBackground?  I have a list of items that all have different statuses and I want to change the background to correspond with the status.  From what I can see all I can do now is change main and alternating background colors.  Is there a way to override this on a cell by cell basis?

Thanks,

Justin

**Comment by newky2k** [comment]
Hi,

sorry for the delay but i will be looking into the tonight and hopefully get a fix quite quickly for you.

thanks
dave

**Comment by newky2k** [comment]
I have now implemented this
